#!/bin/bash

if [ $# -ne 1 ] ; then
	echo "Incorrect arguments input.."
	exit 1
fi

type=$1

if [[ $type == cpu ]]; then
	lscpu
	exit 0
fi

if [[ $type == hw ]]; then
	lshw -short
	exit 0
fi

if [[ $type == pci ]]; then
	lspci
	exit 0
fi

echo "Incorrect arguments input.."
exit 1
